export const valuePx = {
  mobileS: 320,
  mobileM: 375,
  mobileL: 425,
  tabletS: 768,
  tabletM: 830,
  tabletL: 962,
  laptopS: 1024,
  laptopM: 1200,
  laptopL: 1440,
  desktopS: 1920,
  desktopM: 2560,
  desktopL: 3840,
  headerRD: 1230,
};

export const size = {
  mobileS: `${valuePx.mobileS}px`,
  mobileM: `${valuePx.mobileM}px`,
  mobileL: `${valuePx.mobileL}px`,
  tabletS: `${valuePx.tabletS}px`,
  tabletM: `${valuePx.tabletM}px`,
  tabletL: `${valuePx.tabletL}px`,
  laptopS: `${valuePx.laptopS}px`,
  laptopM: `${valuePx.laptopM}px`,
  laptopL: `${valuePx.laptopL}px`,
  desktopS: `${valuePx.desktopS}px`,
  desktopM: `${valuePx.desktopM}px`,
  desktopL: `${valuePx.desktopL}px`,
  headerRD: `${valuePx.headerRD}px`,
};

export const device = {
  mobileS: `(max-width: ${size.mobileS})`,
  mobileM: `(max-width: ${size.mobileM})`,
  mobileL: `(max-width: ${size.mobileL})`,
  tabletS: `(max-width: ${size.tabletS})`,
  tabletM: `(max-width: ${size.tabletM})`,
  tabletL: `(max-width: ${size.tabletL})`,
  laptopS: `(max-width: ${size.laptopS})`,
  laptopM: `(max-width: ${size.laptopM})`,
  laptopL: `(max-width: ${size.laptopL})`,
  desktopS: `(max-width: ${size.desktopS})`,
  desktopM: `(max-width: ${size.desktopM})`,
  desktopL: `(max-width: ${size.desktopL})`,
  headerRD: `(max-width: ${size.headerRD})`,
};
